### ISSUE TITLE
Prerequisites for delivering results

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/tautau-Entanglement#4]
- [x] Resolution plots
    - [x] Suppress the printout
    - [x] Investigate why the smeared polarimetric vectors are always zero in the Ntuples
    - Although we don't need those I find it surprising that the smeared polarimetric vectors are all zero. I don't think that's the intended behavior.
- [x] Aggregate results to produce tables for publication
    - [x] Save results (spin correlation matrix and entanglement variables with uncertainties) to a JSON file
    - [x] Script that reads the JSON files and formats the results in $\LaTeX$
- [x] Ignore unphysical values of concurrence in bootstrap aggregation
    - The issue is that in some events the calculation of concurrence does not work if solving the eigenvalue problem fails or if the eigenvalues pick up a significant imaginary component. It remains to be seen why that's the case, but for the short term we should ignore such unphysical (" $-1$ ") values when bootstrapping them. At the moment we're basically including those unphysical values in the aggregation, which impacts the overall results quite significantly.
- [x] Plot the significance of $R_{CHSH}$ as a function of cut on $\cos\theta^*$
    - [x] It should peak at a certain cutoff value, which we can then impose to obtain the final results
- [x] Verbosity configurable at the command line level
- [x] Merge $a_1$ reconstruction code into main branch

~I'm leaving tasks related to the $a_1$ resonance out for the moment. We can merge the development branch later once the tasks here have been completed.~

**Comment by veelken** [comment]
Hi Karl,

I ran analysis jobs for the dy_lo_pythia8_ext sample for the 3prong branch today. To reduce the computing time, I limited the number of events after cuts to 2000.

My observations are the following:
1) all decay modes give compatible spin correlation matrices on gen level. The spin correlations for the a1_a1 decay channel are somewhat lower, but compatible with the pi_pi and rho_rho decay channels within statistical uncertainties.
2) The different methods to extract the spin correlation matrix C (summation, mlfit, asymmetry, 1d and 2d cross sections) all agree well with each other, on gen as well as on startPos and on kinFit level
3) The resolutions on the tau polarimeter vector is very good in k direction (rms and mean almost zero) and satisfying in r and n direction (small mean, which indicates a small bias, and rms of about 0.18)
4) The distributions of h+ times h- that we sum when we compute the spin correlation matrix C is almost identical for gen, startPos, and kinFit level in k direction, but somewhat different in r and n direction. It seems that the r and n directions get mixed up a bit, which decreases the spin correlation, since C_nn is negative and C_rr is positive
5) It is unclear to me how to reconcile observations 3 and 4. I would have expected that the differences between gen and startPos/kinFit level seen in observation 4 would show up as a bias (mean very different from zero) in observation 3. 

The critical observation is the 4th one. It means that a bias is introduced at the startPos level. The same bias is then also present at the subsequent kinFit level. I did not notice such a bias before, when I ran analysis jobs on the tau+tau -> pi+pi sample produced with TauDecay. My working hypothesis is that either:
- the difference between gen and startPos/kinFit level is caused by the presence of FSR photons and/or the presence of Kaons in the tau decays, which spoil the kinematic reconstruction, in particular the reconstruction of the tautau, tau+, and tau- restframes. I will check this hypothesis by producing Ntuples for the dy_lo_taudecay sample and enable the FSR photon filters for this sample.
- there may be a bias in how I choose between the two solutions (resulting from a two-fold sign ambiguity) in the startPos step. Previously, I took the solution that is more compatible with the track impact parameter, whereas I now take the startPos solution that gives the better chi^2 in the subsequent kinFit step. Choosing the startPos solution with the better chi^2 ensures that the startPos and kinFit solutions are always in 1:1 correspondence with each other, which simplifies code debugging. This choice may potentially introduce a bias though. I will check this hypothesis by running a dedicated (small) Ntuple production with the previous choice of the startPos solution based on track impact parameter compatibility.

P.S. You can find the log-files of my jobs in this directory: /home/veelken/Entanglement/analysis/SuperKEKB/2023Oct15_wSmearing/

**Comment by veelken** [comment]
![makeControlPlots_C_kk](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/29bfc3d9-c0e1-48c9-83a2-9b3414362346)
![makeControlPlots_C_nn](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/4c62c631-dfea-4a65-bec1-beeba3a3aa84)
![makeControlPlots_C_rr](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/7d5b1a31-4467-4fc8-a0c7-2d58e9530680)
![makeResolutionPlots_dy_lo_pythia8_ext_startPosMode_beamAxis_pi_piDecayMode_res_hPlus_k_times_hMinus_k](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/e98c3890-b22e-4346-a9ef-a099f1fbdcd7)
![makeResolutionPlots_dy_lo_pythia8_ext_startPosMode_beamAxis_pi_piDecayMode_res_hPlus_n_times_hMinus_n](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/f613f3ae-3ddd-4fe8-87c4-78969576cb41)
![makeResolutionPlots_dy_lo_pythia8_ext_startPosMode_beamAxis_pi_piDecayMode_res_hPlus_r_times_hMinus_r](https://github.com/HEP-KBFI/tautau-Entanglement/assets/4981326/06989532-3078-4232-a48b-8b92d4ad3876)

**Comment by veelken** [comment]
> Investigate why the smeared polarimetric vectors are always zero in the Ntuples

The reason why the polarimetric vectors are always zero in the gen_smeared case is lines 449 and 467 in [1]. Flagging the tau lepton four-vectors as inValid in the gen_smeared case has the effect that the polarimetric vectors are not computed. The motivation for this logic is that the smearing code smears the "recoil" four-vector, i.e. the sum of the tau+ and tau- four-vectors, but not the tau+ and tau- four-vectors individually. 

I agree the ability to check the spin correlation C at gen_smeared level would be useful.

Lines 126-132 and 151-157 of [2] should propagate the effect of the recoil smearing to the individual tau+ and tau- four-vectors. You could comment-out lines 449+455 and 467+473 in [1] and see if this gives you non-zero polarimetric vectors  for the gen_smeared case.

[1] https://github.com/HEP-KBFI/tautau-Entanglement/blob/main/src/GenKinematicEventBuilder.cc
[2] https://github.com/HEP-KBFI/tautau-Entanglement/blob/main/src/Smearing.cc

**Comment by ktht** [comment]
Hi Christian, thanks for the pointers. Indeed, after uncommenting the lines you highlighted the smeared gen-level polarimetric vectors are no longer zero. This caused excessive warnings in `makeResolutionPlots` (which I have also explicitly suppressed with `isDEBUG` flag even though the underlying issue should be now gone).

If you think that $a_1$ reconstruction code is mature, I could perhaps try merging it into main now and so that you can continue debugging it there. Otherwise it becomes more difficult to resolve merge conflicts as we diverge. The baseline would be that I produce results with the code that's currently in main, then merge your `3prong` branch and reproduce the results. If common results (i.e., for pi and rho decay modes) do not change then the merged branch can be pushed here.

**Comment by veelken** [comment]
Hi Karl,

I ran checks for the 'dy_lo_taudecay' sample today and I confirm that the difference in C_nn and C_rr between gen and startPos/kinFit level is similar in the Pythia8 and TauDecay samples. In my opinion, this rules out the hypothesis that the difference between gen and startPos/kinFit level is caused by FSR photons.

To check the hypothesis that the difference between gen and startPos/kinFit level is due to the choice between the two solutions (resulting from a two-fold sign ambiguity) in the startPos step, I changed the EntanglementNtupleProducer such that only the solution that is more compatible with the track impact parameter is considered in the kinematic fit. This indeed seems to solve the issue! I have attached below [1] the values of C_nn and C_rr that I obtain with:
- choosing the solution with the better chi^2
- choosing the solution that is more compatible with the track impact parameter (TIP)
for tau+tau- -> pi+pi- decays in the TauDecay sample.

These numbers were obtained for just 1000 tau+tau- -> pi+pi- events. I am now running jobs with 10mio event statistics and for the TauDecay and Pythia8 samples, to confirm that the issue is indeed solved. I expect that the check will conclude with a positive result.

Please go ahead and merge the 3prong branch into the master branch. I prefer not to touch the code while I have jobs running.

Thank you,

Christian

- - - - - - - - 

[1]

| Level  | C_nn | C_rr |
| ------------- | ------------- | ------------- |
| gen | -0.3966  | 0.5101 | 
| startPos (chi^2)  | -0.174 | 0.2888 |
| startPos (TIP) | -0.3891 | 0.5037 |
| kinFit (chi^2) | -0.1767 | 0.3045 |
| kinFit (TIP) | -0.3969 | 0.512 |

**Comment by ktht** [comment]
The framework is now set up such that we can run the analysis as a function of cut on $|\cos\theta^\*|$, where $\theta$ refers to the scattering angle in c.o.m. frame. The cut is symmetric in $\theta^\*$ because the entanglement variables are supposed to peak at $\cos\theta^\* = 0$. Furthermore, the acceptance cut of $17^\circ<\theta<150^\circ$ documented in [this book](https://docs.belle2.org/record/1105/files/BELLE2-PUB-PH-2018-001.pdf) becomes symmetric when boosted into c.o.m. frame: $23^\circ < \theta^\* < 167^\circ$ or, equivalently, $|\cos\theta^\*|<0.92$. You can verify this conclusion by running [`acceptanceCalculator`](https://github.com/HEP-KBFI/tautau-Entanglement/blob/main/bin/acceptanceCalculator.cc).

A side note: I noticed that in our code we assume that the electron beam has higher energy than the positron beam and the electron beam directed along +z, see
https://github.com/HEP-KBFI/tautau-Entanglement/blob/d62fb80196346c1e75e9ff7762b14f2fd47c17d7/src/get_localCoordinateSystem.cc#L50
While this is correct for Belle II, it's not quite correct in our simulation: the electron beam has indeed higher energy than the positron beam, but it's directed along -z not +z. I don't know if this subtlety matters, however. I estimated the acceptance boundaries w.r.t. beam that has higher energy (i.e., the electron beam) and not w.r.t. beam that's directed along +z. At the end of the it doesn't really matter because the acceptance cuts become symmetric in c.o.m. frame as I mentioned earlier.

In order to determine the optimal cut in $|\cos\theta^\*|$ that yields the highest significance for QM effects, we have to compute the entanglement variables as a function of cut on $|\cos\theta^\*|$. However, this would cause numerous problems when those measurements are run in a single analysis job as explained in 69a217068bb1cfd053698b9cb1729e2323208f46. The solution (which the commit implements) is to run a separate job for every cut. This is accomplished with `-M scan` argument that's given to `analyzeNtuples.py`. The alternative is `-M inclusive`, which runs the analysis without any cuts on $\cos\theta^\*$. Both modes can be run simultaneously as well (with `-M inclusive scan`). Each analysis job produces a JSON file, which can be easily parsed with the following scripts:
- [`plot_entanglement_vars.py`](https://github.com/HEP-KBFI/tautau-Entanglement/blob/main/scripts/plot_entanglement_vars.py), which produces plots for:
    - various entanglement variables (e.g., `-e Rchsh concurrence steerability`), with only Rchsh being the default;
    - a particular choice of initialization method (i.e., inputs from generator-level or from kinematic fit), tau decay mode and spin analyzer method (`-p individual`) but also for groups by the initialization method (`-p init_method`), tau decay mode (`-p decay_mode`) and spin analyzer method (`-p spin_analyzer`). By default all four options are exercised;
    - entanglement variable itself (`-S excluded`), its significance (`-S only`) or both (`-S both`), which is the default.

    The code can handle missing data points. Example usage, which saves PNG files to a directory that did not exist before:
    ```bash
    plot_entanglement_vars.py -i ~/Entanglement/analysis/SuperKEKB/2023Oct22_1M \
      -o ~/Entanglement/analysis/SuperKEKB/2023Oct22_1M/json_plots \
      -E png
    ```
- [`get_latex_tables.py`](https://github.com/HEP-KBFI/tautau-Entanglement/blob/main/scripts/get_latex_tables.py) creates tables for the publication. Example usage:
    ```bash
    get_latex_tables.py -i ~/Entanglement/analysis/SuperKEKB/2023Oct20 \
      -d pi_pi pi_rho pi_a1 rho_rho rho_a1 a1_a1 | pygmentize -l latex
    ```
    This prints tables where no optimal cut on $|\cos\theta^\*|$ is required. Piping to `pygmentize -l latex` is not strictly needed, but it helps to read the output more clearly. If you have inclusive measurements on fully hadronic events (`had_had`) stored in a separate directory, then those can be included by extending the input argument and drop the explicit list of tau decay modes:
    ```bash
    get_latex_tables.py -i ~/Entanglement/analysis/SuperKEKB/2023Oct20 \
                           ~/Entanglement/analysis/SuperKEKB/2023Oct20_hadHad \
      | pygmentize -l latex
    ```
    Finally, if you have run the analysis in scan mode, then you should have JSON files for each cut on $|\cos\theta^\*|$. Assuming that the optimal cut is, say $|\cos\theta^\*| < 0.30$, then corresponding JSON files end with `absCosTheta0p30.json`. You can run:
    ```bash
    get_latex_tables.py -i ~/Entanglement/analysis/SuperKEKB/2023Oct20 \
                           ~/Entanglement/analysis/SuperKEKB/2023Oct20_hadHad \
      -C absCosTheta0p30 | pygmentize -l latex
    ```
    to produce tables with cuts applied.

Here are a few example plots (out of ~400 possible) based on 1M events:

![plot_Rchsh_genMode_mlfitSpinAnalyzer_byDecayMode](https://github.com/HEP-KBFI/tautau-Entanglement/assets/6233872/2ef97422-58c6-4013-812c-08b838069e2c)
![plot_Rchsh_pi_rhoDecayMode_summationSpinAnalyzer_byMode](https://github.com/HEP-KBFI/tautau-Entanglement/assets/6233872/7a531ff7-f7e0-47bc-8916-504ce0cc1eae)
![plot_RchshSignificance_genMode_pi_piDecayMode_bySpinAnalyzer](https://github.com/HEP-KBFI/tautau-Entanglement/assets/6233872/e60ea40b-0d44-4b8a-97be-9d5ecbb63705)


Since all the ingredients are now there to produce the results for publication, I'm closing the issue.
